name: base

channels:
  - conda-forge
  - defaults

dependencies:
  - numpy 
  - xarray 
  - pandas
  - cartopy 
  - matplotlib 
  - seaborn 
  - geopy 
  - basemap
  - netcdf4
  - cis
  - scipy
  - scikit-learn
  - nc-time-axis
  - PyTables
  - xlrd
  - memory_profiler
  - plotly
  - ipyleaflet
  - rasterio
  - tqdm
  - requests
  - pillow
  - branca
  - geopandas
  - psyplot
  - psy-maps 
  - psyplot-gui 
  - psy-reg 
  - cdsapi 
  - folium
  - basemap-data-hires
  - plotly
  - rasterstats
  - cfgrib
  - cdo
  - nco
  - jupytext
  - pydap
  - papermill
  - plotnine
  - geonum
  - pyaerocom
  - pyresample
  - pip
  - pip:
      - dask_labextension
      - ipydatawidgets
      - sidecar
      - geojsoncontour
      - nbgitpuller
      - pysplit
